general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/thrain/Pictures/Walpapers/lockscreen-active.jpg
    blur_passes = 1
    blur_size = 4
    brightness = 0.75
}

# Reloj
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(e0551fff)
    font_size = 130
    shadow_passes = 2
    shadow_size = 6
    shadow_color = rgba(000000aa)
    font_family = Maple Mono NF
    position = 0, 320
    halign = center
    valign = center
}

# Fecha
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d de %B")"
    color = rgba(93a35aee)
    font_size = 30
    font_family = Maple Mono NF
    position = 0, 200
    halign = center
    valign = center
}

# Mensaje
label {
    monitor =
    text = Welcome back, Thrain
    color = rgba(ecdcc0ff)
    font_size = 42
    font_family = Maple Mono NF
    position = 0, 20
    halign = center
    valign = center
}

# Batería
label {
    monitor =
    text = cmd[update:30000] echo "$(cat /sys/class/power_supply/BAT1/capacity)% $(cat /sys/class/power_supply/BAT1/status)"
    color = rgba(d9a441dd)
    font_size = 18
    font_family = Maple Mono NF
    position = 0, 30
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 200, 36
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    outer_color = rgba(e0551fee)
    inner_color = rgba(1d1a16dd)
    font_color = rgb(ecdcc0)
    fade_on_empty = true
    fail_timeout = 4000
    placeholder_text = <i>contraseña</i>
    check_color = rgb(d9a441)
    fail_color = rgb(b83a2e)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    position = 0, 60
    halign = center
    valign = bottom
}
