.pragma library
// generado desde hypr/frases-thrain.txt (sddm no puede leer el home)
var lista = [
 "Thrain, la montaña no se mueve sola. Vuelve a picar.",
 "El fuego de la forja no espera, Thrain.",
 "Un bloque más, Thrain. Así se construyen reinos.",
 "Thrain no busca motivación: enciende la forja.",
 "Foco, Thrain. Lo demás es ruido.",
 "Los enanos cavaron montañas golpe a golpe. Tú también, Thrain.",
 "Thrain, lo que haces hoy es la piedra de mañana.",
 "Nadie forja acero en un día, Thrain. Pero hoy cuenta.",
 "Silencio, café y un problema difícil. Territorio de Thrain.",
 "Thrain termina lo que empieza.",
 "Menos scroll, más forja, Thrain.",
 "El martillo no duda, Thrain. Tú tampoco.",
 "Thrain, la disciplina pesa menos que el arrepentimiento.",
 "Una hora de foco profundo vale un día entero, Thrain.",
 "El oro está en lo profundo, Thrain. Sigue cavando.",
 "Hazlo aburrido, hazlo diario, hazlo bien, Thrain.",
 "Thrain no compite con nadie. Solo con el Thrain de ayer.",
 "Cada commit es una runa más en la piedra, Thrain.",
 "Thrain, el modelo no se entrena solo.",
 "Fuego bajo, martillo firme, Thrain.",
 "La puerta de la montaña se abre para quien insiste, Thrain.",
 "Thrain, cierra pestañas, abre el problema.",
 "Pequeño progreso sigue siendo progreso, Thrain.",
 "Que el trabajo hable por Thrain.",
 "Thrain, el reino se levanta con constancia, no con suerte.",
 "Respira, Thrain. Un paso, luego el siguiente.",
 "Lock in, Thrain. La forja está caliente."
];
