# Shell
shell zsh

# Font
font_family      Maple Mono NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.5

# Colores neutros
background #1d1a16
foreground #ecdcc0
cursor #e0551f
cursor_shape beam
cursor_blink_interval 0.5

selection_background #3a3128
selection_foreground #ecdcc0

# Paleta neutral
color0  #2a241d
color1  #c9461b
color2  #8a9a5b
color3  #d9a441
color4  #6f8fa6
color5  #b0695a
color6  #7fa39b
color7  #bfae90
color8  #5e5245
color9  #e0551f
color10 #a6b577
color11 #e8bf6a
color12 #8fabbf
color13 #c98470
color14 #9dbdb5
color15 #ecdcc0

# Transparencia
background_opacity 0.85
background_blur 15

# Ventana
window_padding_width 12
confirm_os_window_close 0
enable_audio_bell no

# Tab bar
tab_bar_edge top
tab_bar_style separator
tab_separator " │ "
active_tab_foreground   #e0551f
active_tab_background   #1d1a16
inactive_tab_foreground #5e5245
inactive_tab_background #1d1a16
tab_bar_background      #1d1a16

# Atajos
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+t new_tab
map ctrl+shift+enter new_window
map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
map ctrl+shift+0 change_font_size all 0

# paleta Tinta
url_color #e2cda8
active_border_color #e0551f
cursor_trail 3
